apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploysafe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploysafe
  template:
    metadata:
      labels:
        app: deploysafe
    spec:
      containers:
        - name: deploysafe-container
          image: purvaawankhede/deploysafe-app:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5